// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {cli} from '../models';

export function AcceptIncomingFile(arg1:number):Promise<void>;

export function CloseWindow():Promise<void>;

export function ConfirmEnroll():Promise<cli.EnrollResult>;

export function DefaultRepoPath():Promise<string>;

export function FinishInit():Promise<cli.InitResult>;

export function FinishLink():Promise<Array<cli.LinkedFile>>;

export function FinishPromote():Promise<cli.PromoteResult>;

export function GetConfig():Promise<cli.ConfigInfo>;

export function GetCurrentIndex():Promise<number>;

export function GetDaemonStatus():Promise<string>;

export function GetDiffContent():Promise<string>;

export function GetPendingWarnings():Promise<Array<string>>;

export function GetStatus():Promise<cli.StatusInfo>;

export function GetTotalDiffs():Promise<number>;

export function HasDiff():Promise<boolean>;

export function InstallDaemon():Promise<void>;

export function IsInitialized():Promise<boolean>;

export function NextDiff():Promise<void>;

export function PickDirectory():Promise<string>;

export function PickFileToEnroll():Promise<string>;

export function PreviousDiff():Promise<void>;

export function ResolveBranchCollision(arg1:boolean):Promise<void>;

export function ResolveDivergedFile(arg1:number,arg2:boolean):Promise<void>;

export function StartDaemon():Promise<void>;

export function StartEnroll(arg1:string):Promise<cli.EnrollStartInfo>;

export function StartInitLocal(arg1:string,arg2:string):Promise<cli.InitStartInfo>;

export function StartInitRemote(arg1:string,arg2:string):Promise<cli.InitStartInfo>;

export function StartLink(arg1:boolean):Promise<cli.LinkStartInfo>;

export function StartPromote():Promise<cli.PromoteStartInfo>;

export function StopDaemon():Promise<void>;

export function SubmitReportIssue(arg1:string):Promise<cli.ReportIssueResult>;

export function UninstallDaemon():Promise<void>;
