// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {cli} from '../models';

export function AcceptIncomingFile(arg1:number):Promise<void>;

export function CloseWindow():Promise<void>;

export function ConfirmEnroll():Promise<cli.EnrollResult>;

export function FinishLink():Promise<Array<cli.LinkedFile>>;

export function GetConfig():Promise<cli.ConfigInfo>;

export function GetCurrentIndex():Promise<number>;

export function GetDaemonStatus():Promise<string>;

export function GetDiffContent():Promise<string>;

export function GetPendingWarnings():Promise<Array<string>>;

export function GetStatus():Promise<cli.StatusInfo>;

export function GetTotalDiffs():Promise<number>;

export function HasDiff():Promise<boolean>;

export function InstallDaemon():Promise<void>;

export function IsInitialized():Promise<boolean>;

export function NextDiff():Promise<void>;

export function PickFileToEnroll():Promise<string>;

export function PreviousDiff():Promise<void>;

export function StartDaemon():Promise<void>;

export function StartEnroll(arg1:string):Promise<cli.EnrollStartInfo>;

export function StartLink(arg1:boolean):Promise<cli.LinkStartInfo>;

export function StopDaemon():Promise<void>;

export function UninstallDaemon():Promise<void>;
