// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {cli} from '../models';

export function CloseWindow():Promise<void>;

export function GetCurrentIndex():Promise<number>;

export function GetDiffContent():Promise<string>;

export function GetStatus():Promise<cli.StatusInfo>;

export function GetTotalDiffs():Promise<number>;

export function HasDiff():Promise<boolean>;

export function IsInitialized():Promise<boolean>;

export function NextDiff():Promise<void>;

export function PreviousDiff():Promise<void>;
