// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AcceptIncomingFile(arg1) {
  return window['go']['cli']['App']['AcceptIncomingFile'](arg1);
}

export function CloseWindow() {
  return window['go']['cli']['App']['CloseWindow']();
}

export function ConfirmEnroll() {
  return window['go']['cli']['App']['ConfirmEnroll']();
}

export function FinishLink() {
  return window['go']['cli']['App']['FinishLink']();
}

export function GetConfig() {
  return window['go']['cli']['App']['GetConfig']();
}

export function GetCurrentIndex() {
  return window['go']['cli']['App']['GetCurrentIndex']();
}

export function GetDaemonStatus() {
  return window['go']['cli']['App']['GetDaemonStatus']();
}

export function GetDiffContent() {
  return window['go']['cli']['App']['GetDiffContent']();
}

export function GetPendingWarnings() {
  return window['go']['cli']['App']['GetPendingWarnings']();
}

export function GetStatus() {
  return window['go']['cli']['App']['GetStatus']();
}

export function GetTotalDiffs() {
  return window['go']['cli']['App']['GetTotalDiffs']();
}

export function HasDiff() {
  return window['go']['cli']['App']['HasDiff']();
}

export function InstallDaemon() {
  return window['go']['cli']['App']['InstallDaemon']();
}

export function IsInitialized() {
  return window['go']['cli']['App']['IsInitialized']();
}

export function NextDiff() {
  return window['go']['cli']['App']['NextDiff']();
}

export function PickFileToEnroll() {
  return window['go']['cli']['App']['PickFileToEnroll']();
}

export function PreviousDiff() {
  return window['go']['cli']['App']['PreviousDiff']();
}

export function StartDaemon() {
  return window['go']['cli']['App']['StartDaemon']();
}

export function StartEnroll(arg1) {
  return window['go']['cli']['App']['StartEnroll'](arg1);
}

export function StartLink(arg1) {
  return window['go']['cli']['App']['StartLink'](arg1);
}

export function StopDaemon() {
  return window['go']['cli']['App']['StopDaemon']();
}

export function UninstallDaemon() {
  return window['go']['cli']['App']['UninstallDaemon']();
}
