// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseWindow() {
  return window['go']['cli']['App']['CloseWindow']();
}

export function GetConfig() {
  return window['go']['cli']['App']['GetConfig']();
}

export function GetCurrentIndex() {
  return window['go']['cli']['App']['GetCurrentIndex']();
}

export function GetDiffContent() {
  return window['go']['cli']['App']['GetDiffContent']();
}

export function GetStatus() {
  return window['go']['cli']['App']['GetStatus']();
}

export function GetTotalDiffs() {
  return window['go']['cli']['App']['GetTotalDiffs']();
}

export function HasDiff() {
  return window['go']['cli']['App']['HasDiff']();
}

export function IsInitialized() {
  return window['go']['cli']['App']['IsInitialized']();
}

export function NextDiff() {
  return window['go']['cli']['App']['NextDiff']();
}

export function PreviousDiff() {
  return window['go']['cli']['App']['PreviousDiff']();
}
