// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseWindow():Promise<void>;

export function GetCurrentIndex():Promise<number>;

export function GetDiffContent():Promise<string>;

export function GetTotalDiffs():Promise<number>;

export function Greet(arg1:string):Promise<string>;

export function HasDiff():Promise<boolean>;

export function NextDiff():Promise<void>;

export function PreviousDiff():Promise<void>;
